server:
  port: 8080

spring:
  application:
    name: zuul

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    cached-request:
      path: /cache**
      serviceId: cache_service
      stripPrefix: false